version: '{build}'
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

configuration: Release

install:
- cmd: >-
    dotnet restore

build_script:
- ps: >-
    $major = 0
    $minor = 1
    $patch = 0
    $version = "$major.$minor.$patch"

    dotnet build --configuration Release /property:Version=$version

    dotnet pack --configuration Release /property:Version=$version --no-build src\OddJob\OddJob.csproj --include-symbols

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

test_script:
- ps: dotnet test --configuration Release --no-build test\OddJob.Tests\OddJob.Tests.csproj

artifacts:
- path: src\OddJob\bin\Release\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: zU+yoH7wuMiO8KnnAUtT6TEHibuHUhO6nczepmCvHmcvXox6IICFCx7AA4F9AK7o
  on:
    branch: master
    appveyor_repo_tag: true

skip_commits:
  files:
    - README.md