version: 0.0.{build}
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

configuration: Release

install:
- cmd: >-
    dotnet restore

build_script:
- ps: >-
    dotnet build --configuration Release /property:Version=$env:appveyor_build_version

    dotnet pack --configuration Release --no-build OddJob\OddJob.csproj --include-symbols

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

test_script:
- ps: dotnet test --configuration Release --no-build OddJob.Tests\OddJob.Tests.csproj

artifacts:
- path: OddJob\bin\Release\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: zU+yoH7wuMiO8KnnAUtT6TEHibuHUhO6nczepmCvHmcvXox6IICFCx7AA4F9AK7o
  on:
    branch: master