version: 1.0.{build}
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

configuration: Release
platform: Any CPU

install:
- cmd: >-
    dotnet restore

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

test_script:
- ps: dotnet test --no-build OddJob.Tests/OddJob.Tests.csproj
