version: '{build}'
image: Visual Studio 2017

environment:
  version: 0.1.0

pull_requests:
  do_not_increment_build_number: true

configuration: Release

install:
- cmd: >-
    dotnet restore

build_script:
- ps: >-
    dotnet build --configuration Release /property:Version=$env:version

    dotnet pack --configuration Release /property:Version=$env:version --no-build src\OddJob\OddJob.csproj --include-symbols

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

test_script:
- ps: dotnet test --configuration Release --no-build test\OddJob.Tests\OddJob.Tests.csproj

artifacts:
- path: src\OddJob\bin\Release\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: zU+yoH7wuMiO8KnnAUtT6TEHibuHUhO6nczepmCvHmcvXox6IICFCx7AA4F9AK7o
  on:
    branch: master
    appveyor_repo_tag: true
- provider: GitHub
  release: v$env:version
  description: >-
    ## Where to get it
    You can download this release from [nuget](https://www.nuget.org/packages/OddJob/)
  auth_token:
    secure: 2lxXAVjcYtHJ9YhRKD2u8rwZcUFNB0SaJaIgk5CMx+sYgDW61VDSM1mHkac2q3y+
  artifact: /.*\.nupkg/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

skip_commits:
  files:
    - README.md