version: 1.0.{build}
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

init:
- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200  api.nuget.org")'
  
install:
- cmd: >-
    type c:\windows\system32\drivers\etc\hosts
    
    ping api.nuget.org
    
    dotnet restore
build:
  verbosity: minimal

test_script:
- ps: dotnet test --no-build OddJob.Tests/OddJob.Tests.csproj
